
# After registering a name on build.snapcraft.io, commit an uncommented line:
name: scribus-git
base: core24
version: '1.7.0' 
summary: Your Go-To Libre Desktop Publishing Application # 79 char long summary
description: |
  Underneath a user-friendly interface, Scribus supports professional publishing
  features, such as CMYK colors, spot colors, ICC color management and versatile
  PDF creation.
  Scribus has many unexpected touches, such as powerful vector drawing tools, support
  for a huge number of file types via import/export filters, emulation of color
  blindness or the rendering of markup languages like LaTeX or Lilypond inside
  Scribus. The Scribus file format is XML-based and open. Unlike proprietary binary
  file formats, even damaged documents can be recovered with a simple text editor –
  sometimes a challenging problem with other page layout programs. Scribus has been
  translated into more than 25 languages, and more are coming in the future.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  scribus-git:
    plugin: cmake
    source: https://github.com/scribusproject/scribus.git
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX:PATH=/usr
      - -DWANT_GRAPHICSMAGICK:BOOL=YES
      - -DCMAKE_LIBRARY_PATH:PATH=/usr/lib/qt6
      - -DCMAKE_SKIP_RPATH=ON
      - -DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=FALSE
      - -DQT_PREFIX:PATH="/usr"
      - -DWANT_SVNVERSION:BOOL=YES
      - -DWANT_CPP20=ON
      - -DWITH_PODOFO=ON
      - -Dpoppler_INCLUDE_DIR=/usr/include/poppler # Explicitly set the include directory for Poppler
    build-packages:
      - git
      - cmake
      - build-essential
      - libboost-all-dev
      - libcairo2-dev
      - libfontconfig1-dev
      - libfreetype-dev
      - libgraphicsmagick++1-dev
      - libharfbuzz-dev
      - hicolor-icon-theme
      - libhunspell-dev
      - libicu-dev
      - liblcms2-dev
      - libcdr-dev
      - libcups2-dev
      - libfreehand-dev
      - libjpeg-dev
      - libjxl-dev
      - libmspub-dev
      - libpagemaker-dev
      - libpng-dev
      - librevenge-dev
      - libtiff-dev
      - libvisio-dev
      - libqxp-dev
      - libxml2-dev
      - libzmf-dev
      - libopenscenegraph-dev
      - libssl-dev
      - libpodofo-dev
      - libpoppler-dev
      - python3-dev
      - qt6-base-dev # Added this line for Qt6 base development
      - qt6-base-dev-tools
      - qt6-declarative-dev
      - qt6-5compat-dev
      - qt6-tools-dev
      - qt6-svg-dev
      - zlib1g-dev
    stage-packages:
      - libboost1.74-all-dev
      - libcairo2
      - libfontconfig1
      - libfreetype6
      - libgraphicsmagick++-q16-12t64
      - libharfbuzz0b
      - libhunspell-1.7-0
      - libicu-dev
      - liblcms2-2
      - libcdr-0.1-1
      - libcups2t64
      - libfreehand-0.1-1
      - libjpeg8
      - libjxl0.7
      - libmspub-0.1-1
      - libpagemaker-0.0-0
      - libpng16-16t64
      - librevenge-0.0-0
      - libtiff5-dev
      - libvisio-0.1-1
      - libqxp-0.0-0
      - libxml2
      - libzmf-0.0-0
      - libopenscenegraph-dev
      - libssl3t64
      - libpodofo0.9.8t64
      - libpoppler-glib8t64
      - libpoppler-cpp-dev
      - python3
      - qt6-base-dev # Added this line for Qt6 base development
      - qt6-base-dev-tools
      - qt6-declarative-dev
      - qt6-5compat-dev
      - qt6-tools-dev # Added this line for Qt6LinguistTools
      - qt6-svg-dev # Added this line for Qt6Svg
      - libxkbcommon-dev # Added this line for XKB
      - zlib1g

apps:
  scribus-git:
    command: bin/scribus-git
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - opengl
      - home
      - network
      - cups-control
      - removable-media
