
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: scribus-git
  version: '1.7.0' 
  summary: Your Go-To Libre Desktop Publishing Application # 79 char long summary
  description: |
     Underneath a user-friendly interface, Scribus supports professional publishing
     features, such as CMYK colors, spot colors, ICC color management and versatile
     PDF creation.

     Scribus has many unexpected touches, such as powerful vector drawing tools, support
     for a huge number of file types via import/export filters, emulation of color
     blindness or the rendering of markup languages like LaTeX or Lilypond inside
     Scribus. The Scribus file format is XML-based and open. Unlike proprietary binary
     file formats, even damaged documents can be recovered with a simple text editor –
     sometimes a challenging problem with other page layout programs. Scribus has been
     translated into more than 25 languages, and more are coming in the future.

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  
